config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#home'

  get 'search', to: 'products#search'

  resources :products do
    resources :reviews
  end

  get 'delete', to: 'reviews#destroy', as:
  :review_destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews, dependent: :destroy

  validates :name, :cost, :country_of_origin, presence: true

  before_save :titleize_name

  scope :three_most_recent,  -> { order(created_at: :desc).limit(3)}
  scope :search_by_name, -> (search_name) { where("name like ?", "%#{search_name}%")}

  private
  def titleize(user_input)
    input_array = []
    user_input = user_input.split(' ')
    user_input.each do |word|
      input_array.push((word.capitalize))
    end
    input_array.join(' ')
  end

  def titleize_name
    self.name = self.name.titleize
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, :content_body, :rating, presence: true
  validates :content_body, length: { in: 50..250 } 
end  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :except => [:home, :index, :show] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def home
    @products = Product.all.three_most_recent
    render :home
  end

  def index
    @products = Product.order(:name).page(params[:page])
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
      if @product.save
        flash[:notice] = "New Product Created Successfully"  #Think about adding string interpolation for product name.
        redirect_to products_path
      else
        flash[:alert] = "There was an error while creating product"
        render :new
      end
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:id])
      if @product.update(product_params)
         flash[:notice] = "Product Updated Successfully"
         redirect_to products_path
      else
        flash[:alert] = "There was an error while updating product"
        render :edit
      end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "This Product has been deleted"
    redirect_to products_path
  end

  def search
    @products = Product.search_by_name(params[:product][:name].titleize)
    render :search
  end

  private

  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :except => [:home, :index, :show] 
  before_action :authenticate_user!, :except => [:create, :new, :show] do
    redirect_to new_user_session_path unless current_user && current_user.admin  
  end
  
  def new 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end
  
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
      if @review.save
        flash[:notice] = "New Review Created Successfully"  #Think about adding string interpolation for Review name.
        redirect_to product_path(@product)
      else
        flash[:alert] = "There was an error while creating Review"
        render :new
      end
  end 

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end
  
  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end  
  
  def update
    @review = Review.find(params[:id])
      if @review.update(review_params)
         flash[:notice] = "Review Updated Successfully"  #Think about adding string interpolation for Review name.
         redirect_to product_path(@review.product)
      else
        flash[:alert] = "There was an error while updating Review"
        render :edit
      end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review Deleted"
    redirect_to product_path(@review.product)
  end  
  
  private
    def review_params
      params.require(:review).permit(:author, :content_body, :rating)
    end  
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<div class="content--container">
  <%= render "layouts/errors", :object => @product %>

  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :cost %>
    <%= f.text_field :cost %>
    <%= f.label :country_of_origin %>
    <%= f.text_field :country_of_origin %>
    <%= f.submit %>
  <% end %>

</div>

app/views/layouts/_review_form.html.erb
<div class="content--container">
  <%= render "layouts/errors", :object => @review %>

  <%= form_for [@product, @review] do |f| %>
    <%= f.label :author %> <br>
    <%= f.text_field :author %> <br>
    <%= f.label :content_body %> <br>
    <%= f.text_area :content_body, size: "50x10" %> <br>
    <%= f.label :rating %>
    <%= f.select(:rating, options_for_select([[1, 1], [2, 2], [3,3], [4,4], [5,5]])) %> <br>
    <br> <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marios Food Products</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header--container">
      <div class="row">
        <div class="col-md-4">
          <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong><br>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </p>
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <%= render partial: "layouts/search_form" %>
        </div>
      </div>
    </div>

    <% flash.each do |type, msg|%>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

      <%= yield %>

  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/home.html.erb
<div class="content--container">
  <h1 class="text-center">Welcome to Mario's</h1>
  <h4 class="text-center">Explore the cuisines of the world with our near limitless culinary products</h4>
  <br>
  <br>
  <div class="row">
    <div class="col-md-4">
      <% if @products.three_most_recent %>
        <h4>New Arrivals:</h4>

        <% @products.each do |product| %>
          <ul>
            <li>
              <%= link_to product.name, product_path(product) %>
            </li>
          </ul>
        <% end %>
      <% else %>
        <p>No reviews are listed for this product.</p>
      <% end %>
    </div>
  </div>

<br>
<br>
<br>
<br>
<p><%= button_to "View products", products_path, :class => "button", :method => :get %></p>
<p><%= button_to "Create new product", new_product_path, :class => "button", :method => :get %></p>

app/views/products/index.html.erb
<div class="content--container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Products</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="box col-md-5">
      <% if @products.any? %>
        <ul>
          <% @products.each do |product| %>
            <li><%= link_to product.name, product_path(product) %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no products yet.</p>
      <% end %>
    </div>
  </div>
  <br>
  <br>

  <div class="row">
    <div class="col-5">
    </div>
      <%= button_to "Create new product", new_product_path, :class => "button", :method => :get %>
      <%= button_to "Return to Home", root_path, :class => "button", :method => :get %>
    </div>
  <div class="row">
    <div class="col-12 text-center">
      <p><%= paginate @products %></p>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1 class="text-center">New Product</h1>

<%= render "layouts/product_form" %>

<p><%= link_to "Return to View Products", products_path %></p>

app/views/products/show.html.erb
<div class="content--container">
  <h1>Product: <%= @product.name %></h1>
  <h3>Cost: $<%= @product.cost %></h3>
  <h3>Source Country: <%=@product.country_of_origin %>

  <% if @product.reviews.any? %>
    <h4>Here are the reviews for this product:</h4>

    <% @product.reviews.each do |review| %>
      <ul>
        <li>
          <%= link_to review.author, product_review_path(@product, review) %>
        </li>
      </ul>
    <% end %>
  <% else %>
    <p>No reviews are listed for this product.</p>
  <% end %>

  <p><%= link_to "Add a review", new_product_review_path(@product) %></p>

  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete product", product_path(@product),
                          :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>

  <p><%= link_to "Return to products", products_path %></p>
</div>

app/views/reviews/new.html.erb
<h1 class="text-center">Add a Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Author:<%= @review.author %></h1>
<h5>Review:<%= @review.content_body %></h5>
<h3>Rating:<%= @review.content_body %></h3>


<p><%= link_to "Edit", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>